name: Secret
on: workflow_dispatch

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: test
        env:
            API_KEY: ${{secrets.API_KEY}}
        steps:
            - run: echo "La clé est ". $API_KEY
